export const CITYS = [
    {
        code: '1100',
        city: '北京'
    }, {
        code: '1200',
        city: '天津'
    }, {
        code: '1300',
        city: '河北'
    }, {
        code: '1400',
        city: '山西'
    }, {
        code: '1500',
        city: '内蒙古'
    }, {
        code: '2100',
        city: '辽宁'
    }, {
        code: '2102',
        city: '大连'
    }, {
        code: '2200',
        city: '吉林'
    }, {
        code: '2300',
        city: '黑龙江'
    }, {
        code: '3100',
        city: '上海'
    }, {
        code: '3200',
        city: '江苏'
    }, {
        code: '3300',
        city: '浙江'
    }, {
        code: '3302',
        city: '宁波'
    }, {
        code: '3400',
        city: '安徽'
    }, {
        code: '3500',
        city: '福建'
    }, {
        code: '3502',
        city: '厦门'
    }, {
        code: '3600',
        city: '江西'
    }, {
        code: '3700',
        city: '山东'
    }, {
        code: '3702',
        city: '青岛'
    }, {
        code: '4100',
        city: '河南'
    }, {
        code: '4200',
        city: '湖北'
    }, {
        code: '4300',
        city: '湖南'
    }, {
        code: '4400',
        city: '广东'
    }, {
        code: '4403',
        city: '深圳'
    }, {
        code: '4500',
        city: '广西'
    }, {
        code: '4600',
        city: '海南'
    }, {
        code: '5000',
        city: '重庆'
    }, {
        code: '5100',
        city: '四川'
    }, {
        code: '5200',
        city: '贵州'
    }, {
        code: '5300',
        city: '云南'
    }, {
        code: '5400',
        city: '西藏'
    }, {
        code: '6100',
        city: '陕西'
    }, {
        code: '6200',
        city: '甘肃'
    }, {
        code: '6300',
        city: '青海'
    }, {
        code: '6400',
        city: '宁夏'
    }, {
        code: '6500',
        city: '新疆'
    }
];

// eslint-disable-next-line
export const JSENCRYPT_PUBLICKEY = 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDof5+g7CVWjLd65qHH1rBf7+Q01TZi2J+iObXwyCDGrBXaDhC7al2YELDm890kUtqGFfV0og5oPw9k1lIx48NW4og5b1TyV1T2DAmxBOCwQWMAdWJz9pzMUEe4SHkSIzwjmaKaf0rxi3xCNNc7GfSgu4MIAIudUBol2g6vsFPhpQIDAQAB';